services:
  - type: web
    name: extractor-partituras
    env: python
    plan: free
    buildCommand: >
      apt-get update &&
      apt-get install -y --no-install-recommends
      build-essential
      python3-dev
      libjpeg-dev
      zlib1g-dev
      libwebp-dev &&
      pip install --upgrade pip setuptools wheel &&
      pip install --only-binary :all: Pillow opencv-python-headless numpy &&
      pip install Flask
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
